---
# This playbook starts a new builder

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Provision the instance
    register: ec2
    ec2:
      #key_name: test
      wait: false
      group: puiterwijk-atomic-compose-server
      image: ami-080bd47b
      instance_profile_name: puiterwijk-atomic
      instance_type: t2.micro
      region: eu-west-1
      exact_count: 1
      count_tag:
        Name: Puiterwijk-Atomic-Compose-Server
      instance_tags:
        Name: Puiterwijk-Atomic-Compose-Server
      user_data: |
        #cloud-config
        runcmd:
        - /bin/sh -c "curl https://raw.githubusercontent.com/puiterwijk/puiterwijk-Atomic/master/boot.sh | bash"
      volumes:
        - device_name: /dev/sda1
          delete_on_termination: true
          volume_type: gp2
          volume_size: 10
